name: Run CumulusCI Task

on:
  workflow_dispatch:
    inputs:
      task:
        required: true
        type: string
      org:
        required: true
        type: environment

env:
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
  CUMULUSCI_ORG_dev: ${{ secrets.CUMULUSCI_ORG_dev }}

jobs:
  run_task:
    uses: jlantz/CumulusCI-GitHub-Actions/.github/workflows/persistent_org_task.yml@main
    with:
      task: ${{ github.event.inputs.task }}
    secrets:
      CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
      CUMULUSCI_ORG_dev: ${{ secrets.CUMULUSCI_ORG_dev }}
    environment: ${{ github.event.inputs.org }}